[project]
name = "release-please-demo"
version = "1.1.0+7d95936"
description = "Experimenting with release-please."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.6",
]
