[project]
name = "release-please-demo"
version = "1.2.1-92b4aec"
description = "Experimenting with release-please."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.6",
]
