name: Build & Push Docker Image

on:
  pull_request:
    branches:
      - development
      - staging
    paths:
      - '.release-please-manifest.json'  # only build if version changed

permissions:
  contents: read
  packages: write
  pull-requests: write

jobs:
  build-push:
    name: Build & Push Docker Image to GAR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from release-please manifest
        run: |
          VERSION=$(jq -r '.["."]' .release-please-manifest.json)
          echo "VERSION=${VERSION}" >> "${GITHUB_ENV}"

      - name: Determine Image Tag
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: ${{ github.env.VERSION }}

      # TODO: use buildx & enable caching

      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
