name: Promote Artifacts

on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - .release-please-manifest.json  # only release PRs

permissions:
  contents: read
  packages: write

jobs:

  identify-builds:
    name: Extract versions to promote from staging manifest
    # small risk of race condition here!
    # if release PR merges at same time as a non-release PR merges,
    # thus opening a new release PR and updating staging,
    # this job could read the newer manifest on staging rather than the one from the merged release PR
    # unlikely since checkout should be faster than creating a release PR, doing a build, and updating staging
    # fix would be to read some artifact emitted by the build or staging workflow
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.identify.outputs.packages }}
    steps:

      - name: Checkout staging branch
        uses: actions/checkout@v4
        with:
          ref: staging

      - name: Identify packages to build
        id: identify
        run: |
          packages=$(jq -c '
            to_entries
            | map(select(.value | test("-[a-f0-9]{7}$")))
            | to_entries
          ' .release-please-manifest.json)

          echo "Packages with git hash suffixed: $packages"
          echo "packages=$packages" >> $GITHUB_OUTPUT

  promote-api:
    name: Promote API container
    runs-on: ubuntu-latest
    needs: identify-builds
    if: ${{ fromJSON(needs.identify-builds.outputs.packages).api != '' }}
    steps:

      - name: Identify Versions
        id: versions
        run: |
          prerelease=$(echo ${{ needs.identify-builds.outputs.packages }} | jq -r '.api')
          release=${prerelease_version%-*}

          echo "Promoting ${prelease} -> ${release}"
          echo "prerelease=${prerelease}" >> $GITHUB_OUTPUT
          echo "release=${release}" >> $GITHUB_OUTPUT

      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Promote API container ${{ steps.versions.outputs.prelease }} to ${{ steps.versions.outputs.release }}
        run: |
          docker pull ${{ steps.versions.outputs.prelease }}
          docker tag ${{ steps.versions.outputs.prelease }} ${{ steps.versions.outputs.release }}
          docker push ${{ steps.versions.outputs.release }}

  update-branches:
    needs:
      - promote-api
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
          - staging
          - production
    steps:

      - name: Checkout ${{ matrix.branch }} branch
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

      - name: Override merge from PR branch
        uses: ./.github/actions/git-override-merge
        with:
          source-branch: ${{ github.ref }}

      - name: Push override commit
        run: |
          git push origin ${{ matrix.branch }}:${{ matrix.branch }}
