name: Create Release PR with release-please

on:
  push:
    branches:
      - main
  workflow_dispatch:  # just in case

permissions:
  contents: write
  pull-requests: write
  checks: read
  statuses: read
  actions: read
  repository-projects: read

jobs:
  release-please-plus:
    uses: ./.github/workflows/release-please-plus.yaml
    with:
      target-branch: main
    secrets:
      pat: ${{ secrets.RELEASE_PLEASE_PAT }}
